import type { Metadata } from 'next'
import { ibmsans } from './ui/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isRTL = true;
  const  dirc = (isRTL) ? 'rtl' : 'ltr';
  return (
    <html lang="ar">
      <body dir={dirc} className={`${ibmsans.className} bg-slate-50 `}>{children}</body>
    </html>
  )
}
