import type { Metadata } from "next";
import { ibmsans } from "../components/ui/fonts";
import "./globals.css";
import { Toaster } from "../components/ui/toaster";
import { cn } from "../lib/utils";
import Navbar from "../components/navigation/navbar";
import Header from "@/components/navigation/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isRTL = true;
  const dirc = isRTL ? "rtl" : "ltr";
  return (
    <html lang="ar" className=" h-full">
      <body
        dir={dirc}
        className={cn("relative h-full bg-slate-50", ibmsans.className)}
      >
        <div className="relative flex flex-col min-h-screen">
          <Header/>
          {/* <Navbar /> */}
          <div className="felx-grow flex-1">{children}</div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
